# Generated by Django 5.1.4 on 2024-12-26 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_examplemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
