# Generated by Django 5.1.5 on 2025-01-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_delete_examplemodel"),
        ("classroom", "0003_alter_classroom_class_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="classrooms",
            field=models.ManyToManyField(
                related_name="enrolled_students", to="classroom.classroom"
            ),
        ),
    ]
