# Generated by Django 5.1.6 on 2025-02-28 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_image',
            field=models.ImageField(blank=True, null=True, upload_to='face_recognition/'),
        ),
        migrations.AddField(
            model_name='user',
            name='face_recognition_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_vector', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embeddings',
            },
        ),
    ]
