# Generated by Django 5.1.5 on 2025-01-24 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classroom", "0008_alter_exam_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="teacher",
        ),
    ]
