# Generated by Django 5.1.6 on 2025-03-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0012_exam_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='exam_duration',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_end_time',
            field=models.TimeField(default='23:59:59', help_text='When the exam ends'),
        ),
        migrations.AddField(
            model_name='exam',
            name='visibility_to_students',
            field=models.BooleanField(default=True, help_text='Whether students can see this exam before it starts'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
