# Generated by Django 5.1.6 on 2025-03-15 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0011_alter_question_correct_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('connection_id', models.CharField(blank=True, max_length=100, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='classroom.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('face_missing', 'Face Not Detected'), ('multiple_faces', 'Multiple Faces'), ('unknown_face', 'Unknown Person'), ('looking_away', 'Looking Away'), ('tab_switch', 'Tab Switched'), ('suspicious_motion', 'Suspicious Motion'), ('phone_detected', 'Phone Detected'), ('speaking', 'Speaking Detected'), ('unauthorized_object', 'Unauthorized Object'), ('other', 'Other Violation')], max_length=30)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='monitoring/alerts/')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.examsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['exam', 'is_active'], name='monitoring__exam_id_20895e_idx'),
        ),
        migrations.AddIndex(
            model_name='examsession',
            index=models.Index(fields=['student', 'is_active'], name='monitoring__student_695454_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together={('student', 'exam', 'is_active')},
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['session', 'timestamp'], name='monitoring__session_7e2387_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['is_reviewed'], name='monitoring__is_revi_249452_idx'),
        ),
    ]
