# Generated by Django 5.1.6 on 2025-03-17 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_alert_reviewed_at_alert_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='is_paused',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='pause_reason',
        ),
        migrations.RemoveField(
            model_name='examsession',
            name='paused_at',
        ),
        migrations.DeleteModel(
            name='TeacherAction',
        ),
    ]
